spring:
    application:
        name: sitmun-admin-app
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:./database/sitmundb;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
        continue-on-error: true
    jpa:
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.ddl-auto: create-drop
            hibernate.format_sql: true
            hibernate.naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    h2:
        console:
            enabled: true
